[versions]
# libraries
# https://mvnrepository.com/artifact/org.jsoup/jsoup
jsoup = "1.22.1"
# https://mvnrepository.com/artifact/com.wutka/dtdparser
dtdparser = "1.21"
# https://mvnrepository.com/artifact/commons-io/commons-io
commonsIO = "2.21.0"
# https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305
jsr305 = "3.0.2"
# https://mvnrepository.com/artifact/org.apache.maven/maven-model
mavenModel = "3.9.12"
# https://mvnrepository.com/artifact/commons-codec/commons-codec
commonsCodec = "1.20.0"
# https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
commonsLang3 = "3.20.0"
# https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
commonsCollections4 = "4.5.0"
# https://mvnrepository.com/artifact/jakarta.xml.bind/jakarta.xml.bind-api
jakartaXmlBindApi = "4.0.4"
# https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl
jaxbImpl = "4.0.6"
# https://mvnrepository.com/artifact/org.apache.solr/solr-solrj
# version 9.2.1 is already available but we stick to the version used by Hybris
# see folder hybris\bin\modules\search-and-navigation\solrserver\resources\solr\
# 9.9.0
solrSolrj = "8.11.4"
# https://mvnrepository.com/artifact/com.squareup.moshi/moshi
moshi = "1.15.2"
# https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp/
okhttp = "5.3.2"
# https://central.sonatype.com/artifact/org.jetbrains.kotlinx/kotlinx-serialization-core/1.9.0
serialization = "1.9.0"

# plugins
# https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm
kotlin = "2.3.10"
# https://plugins.gradle.org/plugin/org.jetbrains.changelog
changelog = "2.5.0"
# Dependency: https://plugins.gradle.org/plugin/org.openapi.generator
# Generator: https://openapi-generator.tech/docs/generators/kotlin
openAPIGenerator = "7.19.0"

[libraries]
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commonsIO" }
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commonsCodec" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonsLang3" }
commons-collections4 = { group = "org.apache.commons", name = "commons-collections4", version.ref = "commonsCollections4" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
dtdparser = { group = "com.wutka", name = "dtdparser", version.ref = "dtdparser" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
maven-model = { group = "org.apache.maven", name = "maven-model", version.ref = "mavenModel" }
jakarta-xml-bind-api = { group = "jakarta.xml.bind", name = "jakarta.xml.bind-api", version.ref = "jakartaXmlBindApi" }
jaxb-impl = { group = "com.sun.xml.bind", name = "jaxb-impl", version.ref = "jaxbImpl" }
solr-solrj = { group = "org.apache.solr", name = "solr-solrj", version.ref = "solrSolrj" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
moshi-kotin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
kotlinxJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

[bundles]
commons = ["commons-io", "commons-codec", "commons-lang3", "commons-collections4"]
jaxb = ["jaxb-impl", "jakarta-xml-bind-api"]
openapi = ["moshi", "moshi-adapters", "moshi-kotin", "okhttp"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
openAPIGenerator = { id = "org.openapi.generator", version.ref = "openAPIGenerator" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
